### ISSUE TITLE
AssertionError on Connection

### ISSUE THREAD

**Issue by EnderInvader** [Genhis/KRPC.MechJeb#21]
**Describe the bug**

When using KRPC MechJeb, KRPC connection no longer works and throws an AssertionError. KRPC works as normal when KRPC MechJeb is uninstalled.

**Expected behavior**

No error.

**Code snippet to reproduce it (ideally in Python)**
```
import krpc

conn = krpc.connect(name='Test')
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20405891/229218443-a24458ba-4c3c-4203-96c0-1a860f8df3f0.png)

**Version details**
kRPC.MechJeb: 0.7.0

Kerbal Space Program: 1.12.5
kRPC: 0.5.2
MechJeb2: 2.14.3.0

**Comment by Genhis** [comment]
Thanks for the report. This is a kRPC issue (https://github.com/krpc/krpc/issues/754) which should be fixed in the next kRPC release.

You could try commenting out the asserts or removing pacraged service definitions from kRPC as a workaround, although I haven't tried it. Hopefully the fix is released soon.

**Comment by Genhis** [comment]
This should be fixed in [kRPC 0.5.3](https://github.com/krpc/krpc/releases/tag/v0.5.3).
